# Generated by Django 2.1.2 on 2018-10-17 11:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='LightBulb',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('intensity', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='LightGroup',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Plant',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('humidity', models.FloatField()),
                ('humid_min', models.FloatField()),
                ('last_watered', models.DateTimeField()),
            ],
        ),
        migrations.AddField(
            model_name='lightbulb',
            name='belongs_to_group',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='haas_site.LightGroup'),
        ),
    ]
